# Generated by Django 3.1.6 on 2021-02-20 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True, verbose_name='date')),
                ('body', models.TextField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, null=True, upload_to='pict')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_data', models.CharField(max_length=200)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.blog')),
            ],
        ),
    ]
